<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Untitled Form</a></h1>
		<form id="form_1127653" class="appnitro"  method="post" action="http://lmckee.campbellits.net/ITS470/FinalA/a2.php">
					<div class="form_description">
					
			<h2>Untitled Form</h2>
			<p>This is your form description. Click here to edit.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="state">Select State </label>
		<div>
		<select class="element select medium" id="state" name="state"> 
			<option value="" selected="selected"></option>
<option value="nc" >NC</option>
<option value="oh" >OH</option>
<option value="ca" >CA</option>

		</select>
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="1127653" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
				<a href="http://lmckee.campbellits.net/ITS470/FinalA/a2.php"> A2</a>
				
			
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>